networks:
  immo.net:
    driver: bridge

services:
  adminer:
    image: adminer
    env_file: ./.env
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '8080:8080'
    networks:
      - immo.net

  immo.db:
    image: 'mysql:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./.env
    ports:
      - '3306:3306'
    networks:
      - immo.net

  immo.api:
    image: 'canals/php:latest'
    env_file: ./.env
    ports:
      - '8098:80'
    volumes:
        - ./public:/var/www/html
        - ./src:/var/www
    working_dir: /var/www/
    networks:
      immo.net:
        aliases:
          - immo.api.local
    depends_on:
        - immo.db
